"""empty message

Revision ID: f0087a14e502
Revises: 0dfc2b3c7e61
Create Date: 2025-02-02 11:28:45.015130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0087a14e502"
down_revision: Union[str, None] = "0dfc2b3c7e61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("amount", sa.Float(), nullable=False)
    )
    op.drop_column("transactions", "balance")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "balance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("transactions", "amount")
    # ### end Alembic commands ###
